### ISSUE TITLE
Materializer no_snapshot bug

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#103]
There is a problem with the materializer. It returns {error, no_snapshot} in a case where it should not. i.e., the case where there have never been snapshots or operations in the history of the key being read.

I believe I have fixed it in the no_snapshot_bug branch. I am running the tests now and will make a pull request when I believe its done.

**Comment by bieniusa** [comment]
I am restructuring the code of the materializer_vnode, so beware.
