### ISSUE TITLE
Paper abstract and title

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#108]

**Comment by marc-shapiro** [comment]
How about: (6) Cure: strong semantics meets high availability and low latency

							Marc

**Comment by marc-shapiro** [comment]
How about: (6) Cure: strong semantics meets high availability and low latency

							Marc

**Comment by preguica** [comment]
I would probably avoid using the word strong semantics, as a lot of people
would not agree that the semantics is strong...  more comments on the
abstract + intro tomorrow.

**Comment by bieniusa** [comment]
Guys,

I was serious: Please don’t discuss this on Github.

	Annette




> Am 14.05.2015 um 00:34 schrieb preguica <notifications@github.com>:
> 
> I would probably avoid using the word strong semantics, as a lot of people
> would not agree that the semantics is strong... more comments on the
> abstract + intro tomorrow.
> 
> 
> On Wed, May 13, 2015 at 11:24 PM, marc-shapiro <notifications@github.com>
> wrote:
> 
> > How about: (6) Cure: strong semantics meets high availability and low
> > latency
> >
> > Marc
> >
> > > Le 13 mai 2015 à 19:13, Alejandro Zlatko Tomsic <

**Comment by cmeiklejohn** [comment]
Issue is closed!
