### ISSUE TITLE
Possible issue about mixing disk_log and dets

### ISSUE THREAD

**Issue by marsleezm** [SyncFree/antidote#120]
In the evaluation branch, most of the code uses disk_log, however dets are still used in handle_info function. I am not sure if this is a bug, just posting it for not forgetting so someone responsible for the code can verify them afterwards.

**Comment by tcrain** [comment]
The calls to dets marsleezm is referencing were in the old interdc protocol, the new interdc recovers missing transactions from disk log and no longer uses dets
https://github.com/SyncFree/antidote/pull/174
