### ISSUE TITLE
No easy way to turn off SI certification check

### ISSUE THREAD

**Issue by tcrain** [SyncFree/antidote#131]
Right now most the the objects in antidote are CRDTs that don't need to abort in the presence of concurrent updates.  For these objects there should be no SI certification check as it will just cause unnecessary aborts and wasted CPU cycles.

Currently the only way to turn on or off the certification check it to comment it out in the code.  Some branches have it commented out and some do not.  Maybe there is a better way to do this?  For example only do certification check depending on the object?  We will have to precisely define what kind of consistency we want to guarantee though.

**Comment by cmeiklejohn** [comment]
+1, we *need* this.

**Comment by tcrain** [comment]
Following the mumble discussion today, the next step for this is to come up with a specification for how and when the certification check should be used.  Implementing the decided specification will also solve issue 130 ( https://github.com/SyncFree/antidote/issues/130 ).

Some initial thoughts for the specification:

- The certification check should be disabled by default as we are targeting CRDTs and causality.
- Choosing whether to certify or not could be done based on object type (for example the bounded counter would have it enabled, while the other CRDTs would not).
- Another possibility would be to give the programmer the ability to enable or disable it in application code.  This might be per object, per transaction, per workload.

**Comment by marc-shapiro** [comment]
The begin_transaction construct contains a parameter "red/blue".  Blue has no certification check.  Furthermore, per CRDT type, operations are classified as red or blue (possibly depending on parameters).   A blue transaction may not contain any red operations.

						Marc

**Comment by preguica** [comment]
I agree - ideally you would want to be able to specify that a transaction
should have SI check or not, but then you would like to be able to say that
the check is only done for some objects (those where you have executed one
operation that requires strong consistency).

Having said that, all this flexibility might not be that easy to code and
some compromise may be needed - e.g. whenever a strong object (e.g. bounded
counter) is used, SI check is done (independently of the executed
operation).

**Comment by bieniusa** [comment]
In addition, if you offer so much flexibility, then the programming model becomes very complex.
The semantics of transactions with respect to their isolation would become non-composable, I guess.

Is this really what we want?

For example, you have the SI check for an object enabled in one txn but not in another. 
What does this mean?
Programmers are having lots of trouble understanding SI - they seem to prefer either strong (i.e. serializable) or kind of no guarantees.

	Annette

**Comment by marc-shapiro** [comment]
> Le 30 juin 2015 à 18h33, Annette Bieniusa <notifications@github.com> a écrit :
> 
> For example, you have the SI check for an object enabled in one txn but not in another. 

That would not be possible with the API I propose: methods are classified as red or blue, and a red operation requires a red transaction.

						Marc
