### ISSUE TITLE
Single receiver per DC for interDC traffic

### ISSUE THREAD

**Issue by tcrain** [SyncFree/antidote#133]
In a DC, all traffic received from all other DCs goes through a single machine.  While this machine doesn't do the full processing of the transaction, it still has to deserialise the message and forward it to the proper destination.

This can be a problem as this machine is also responsible for an equivalent amount of the key space as other machines (for performing local transactions), so it will end up doing much more work than the others, possibly becoming a bottleneck.

**Comment by Eipifi** [comment]
One of the possible solutions is to broadcast the transaction directly to partitions, not to the master inter-dc node. This can be done cleanly with pubsub, at the expense of a significant number of tcp connections.

**Comment by tcrain** [comment]
Seems good to me.

Though the number of tcp connections would remain the same I believe because currently each partition creates a tcp connection (just to a single destination).  So if you have 2 DCs each with 10 partitions, you would have 20 tcp connections.  With pubsub each partition would connect to the corresponding partition on the receiver (partitions are the same across DCs), so it would also need 20 connections, correct?

**Comment by Eipifi** [comment]
I don't think so - correct me if I'm wrong.

N = number of DCs, P = number of partitions.

Right now we have one connection for each pair of DCs, this gives us (N)*(N-1)/2. Then there are (P-1) connections for sending the transactions inside the DC, from master to partitions. This gives us N * (P-1) intraDC connections (these connections are hidden by erlang OTP, but it still counts). In total, N * (P-1 + (N-1)/2), which is roughly equal to N(N+P).

With the pubsub approach, each partition in each DC would need to subscribe to each other DC. This gives us N^2*P. At this point the intraDC connections are negligible. 

But this still assumes that each DC delegates one node for pushing transactions to subscribers. Removing the publisher node (and thus completely decentralizing our approach) would require each partition to subscribe to each partition in other DCs, which means N*P * ((N-1)*P), which is roughly equal to (NP)^2.

Heavy, but doable. Let's say we have a 6 DC setup with 8 partitions per DC. Each partition would need to maintain (N-1)P=40 subscription connections plus the same number of publisher connections, which gives us 80 TCPs per partition.

**Comment by Eipifi** [comment]
On a second thought, a different approach is possible. It would involve creating N(N-1) * P connections between matching partitions in different DCs. Imagine P "parallel" cliques between DCs. This way each partition involved in a transaction would be responsible for pushing the transaction to its matching nodes in different DCs. No central point, reasonable number of connections. I think that's the way to go.

**Comment by tcrain** [comment]
Each partition only needs to subscribe to one other partition per DC, because the key space is the same in each DC.  I.e. if partition A in DC1 replicates keys x,y then partition A in DC2 replicates key x,y.

So each partition maintains N-1 subscription connections [times 2 if they are one way] (this is also how it is done currently).

I think you are assuming that the partitions are different per DC? Is that why you need (N-1)P connections per partition?

**Comment by Eipifi** [comment]
Yep, that's what I had in mind in the second post. I was assuming that partitions are different.

**Comment by marc-shapiro** [comment]
But this won't be true anymore with your (Tyler's) partial replication protocol, correct?  So we must still try to find an approach that scales.  

					Marc

**Comment by tcrain** [comment]
Yes, it's not true for the partial replication protocol.  Also the partial replication needs to have additional tcp connections open when performing reads on items that are not replicated at the local DC and are fetched from an external DC.

I guess on the topic the balancing of nodes we should also consider where the transaction coordinators are run, right now the client itself picks a physical node within the DC to send the transaction to.  Maybe a load balancer is helpful?  Or the coordinators could run in separate physical nodes from the nodes that are responsible for the ring.

**Comment by tcrain** [comment]
This issue was fixed in https://github.com/SyncFree/antidote/pull/174
