### ISSUE TITLE
Suggestion to replace erlang:now with os:timestamp

### ISSUE THREAD

**Issue by tcrain** [SyncFree/antidote#151]
We use erlang:now in several places on the critical path of the client operations.  Apparently it uses a global lock to ensure that every call to this gets an increasing timestamp.  This could be a bottleneck.

Suggestion to replace this with os:timestamp.  With this different calls should be able to get the same timestamp, or concurrent processes might be able to read out of order.  For this I think we have to be careful when creating new transactions and when calculating the stable time per partition, but it should be solvable.

**Comment by Eipifi** [comment]
erlang:now/0 is deprecated in erlang documentation, so we should change it anyway.
http://www.erlang.org/doc/man/erlang.html#now-0

**Comment by tcrain** [comment]
Ah nice.  Maybe we can use this then?
http://www.erlang.org/doc/man/erlang.html#monotonic_time-0
Since its not strictly increasing, we might calculate the stable snapshot using < instead of =< for example.  I think we already do this?

Also maybe we should ensure transaction ids are unique.  Right now they are {time, pid}, but the same process could make two transactions with the same time if it is faster than time increases!

**Comment by tcrain** [comment]
Oh no, maybe this instead:
http://www.erlang.org/doc/man/erlang.html#system_time-0

The previous one only gives an offset from some random point in time.
And we have to choose the correct time warp option I guess:
http://www.erlang.org/doc/apps/erts/time_correction.html#Time_Warp_Modes

**Comment by tcrain** [comment]
I ran a benchmark just to check with 3 nodes, and it showed about a 6-7% performance increase by using os:timestamp over erlang:now.  I guess this would be more significant with more machines.

The problem is that os:timestamp isn't safe for the clocksi protocol.  Unfortunately the functions that would be safe as described my previous post are not available in the version of erlang we are currently using.  They are available in OTP 18 as described here:
http://www.erlang.org/doc/apps/erts/time_correction.html

Actually here it also says 
"However, you are strongly encouraged to use the new API instead of the old API based on erlang:now/0. erlang:now/0 has been deprecated since it is and forever will be a scalability bottleneck."

So maybe we should upgrade.

**Comment by bieniusa** [comment]
The issue with upgrading is in the dependency with riak-core.

So, upgrading would be non-trivial (unless we get away from riak core).

**Comment by aletomsic** [comment]
Maybe upgrading riak core to comply with erlang v.18 would not be that hard.
Other idea could be to use logical physical clocks? I think the design removes the issue Tyler mentions, but I am not totally sure about it.
Can take another look at the paper.

Alejandro Tomsic
