### ISSUE TITLE
Oprga_test fails in reduce_time_tests

### ISSUE THREAD

**Issue by bieniusa** [SyncFree/antidote#162]
There is some issue with the ordering.

{{assertMatch_failed,
     [{module,oprga_test},
      {line,65},
      {expression,"Result1"},
      {pattern,
          "{ ok , [ { ok , a , _ } , { ok , b , _ } , { ok , c , _ } ] }"},
      {value,
          {ok,[{ok,a,{'dev1@127.0.0.1',#Ref<10808.0.0.9644>}},
               {ok,c,{'dev1@127.0.0.1',#Ref<10808.0.0.9655>}},
               {ok,b,{'dev1@127.0.0.1',#Ref<10808.0.0.9651>}}]}}]},

**Comment by santialvarezcolombo** [comment]
The solution for this issue, is in #154. @tcrain is working on the code review comments to finish it.
