### ISSUE TITLE
Update rebar.config to include latest version of antidote_crdt

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#229]
Hi, I've added the antidote_crdt_lwwreg to the list of CRDTs in: 

https://github.com/SyncFree/antidote_crdt/blob/master/src/antidote_crdt.erl#L35

Without that, the type check fails when issuing an operation to that type, as it believes the type does not exist.

What we are missing now is that Antidote's rebar.config points to the latest changes of antidote_crdt. 

Should we build a new release of antidote_crdt? 
So far, I am using, in the PhysiCS branch, this:
https://github.com/SyncFree/antidote/blob/PhysiCS/rebar.config#L12

instead of what master uses: 
https://github.com/SyncFree/antidote/blob/master/rebar.config#L12

**Comment by bieniusa** [comment]
We should probably do this once @peterzeller has updated the antidote_crdt repo.

**Comment by peterzeller** [comment]
The crdt library was updated with #230
