### ISSUE TITLE
Trouble installing antidote

### ISSUE THREAD

**Issue by WoolridgeGrant** [SyncFree/antidote#278]
Hello, 

While trying to install antidote I got an Error 1. Here's what I did : 
- git clone the repo
- install all dependencies
- make rel in the antidote folder

Then I got : 
===> Failed to fetch and copy dep: ({git, "git://github.com/syncfree/antidote_crdt", {tag, "0.0.4"}))
make *** [Makefile:30: rel] Error 1

OS is Archlinux

Thanks in advance

**Comment by bieniusa** [comment]
Hello,
can you explain in more detail what you mean by "install all dependencies"?
"make rel"  should automatically pull all the dependencies on Erlang libraries.

**Comment by WoolridgeGrant** [comment]
Sorry, by "install all dependencies" I meant installing Erlang/OTP 19.0

**Comment by bieniusa** [comment]
Could it have been a temporary unavailability of github?

Older versions of git also seem to have trouble with rebar3, the build system that we use.
Which version of git are you running?

**Comment by bieniusa** [comment]
We upgraded to a newer version of rebar3 which might solve problems with older git installs.
Can you try again with the most recent version of the master branch?

**Comment by WoolridgeGrant** [comment]
> Could it have been a temporary unavailability of github?

I don't think so, I tried it multiple times on different days

I am using git version 2.9.3

I am currently trying with the most recent version of the master branch

**Comment by cmeiklejohn** [comment]
Please try `DEBUG=1 ./rebar3 compile` and provide the output.

**Comment by WoolridgeGrant** [comment]
Well guys it seems to work :

===> Compiling riak_api
===> Compiling rand_compat
===> Compiling antidote_pb
===> Compiling antidote_crdt
===> Compiling antidote
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/woolridgegrant/antidote/_build/default/lib
          /home/woolridgegrant/antidote/ebin
          /home/woolridgegrant/antidote/apps
          /usr/lib/erlang/lib
===> Resolved antidote-0.0.1
===> Including Erts from /usr/lib/erlang
===> release successfully created!

I updated all packages with pacman -Syu but not sure it was related to the problem.
Thank you @bieniusa and @cmeiklejohn for your patience.

**Comment by bieniusa** [comment]
You are welcome! :)

**Comment by cmeiklejohn** [comment]
What do you mean by?

> I updated all packages with pacman -Syu but not sure it was related to the problem.

**Comment by WoolridgeGrant** [comment]
I know someone who had the same issue as me, around 4pm yesterday he told me that make rel was now working.
Meanwhile I had to update my packages for another work.
Then later on I tried make rel again and it worked. 

So I can't tell for sure what solve the problem.

**Comment by cmeiklejohn** [comment]
Can you provide the commands you ran?  My concern is that we haven't tested
antidote with updated deps, and therefore, some functionality may no longer
work if the deps have changed.

**Comment by adilbakkouri** [comment]
![capture d ecran de 2017-02-13 18 36 07](https://cloud.githubusercontent.com/assets/25750468/22895153/d1dbc1ea-f21b-11e6-8b63-b5af6ae5d483.png)
 I have the same error message, here's the output of `DEBUG=1 ./rebar3 compile`

`===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {default,install_deps},
                                                  {default,lock},
                                                  {default,compile}]
===> Verifying dependencies...
===> Fetching antidote_crdt ({git,
                                     "git://github.com/syncfree/antidote_crdt",
                                     {tag,"0.0.5"}})
===> sh info:
	cwd: "/home/adilbak/antidote"
	cmd: git --version

===> 	opts: []

===> Port Cmd: git --version
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> sh info:
	cwd: "/home/adilbak/antidote"
	cmd: git clone git://github.com/syncfree/antidote_crdt .tmp_dir261497953176 -b 0.0.5 --single-branch

===> 	opts: [{cd,"/tmp"}]

===> Port Cmd: git clone git://github.com/syncfree/antidote_crdt .tmp_dir261497953176 -b 0.0.5 --single-branch
Port Opts: [{cd,"/tmp"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

===> sh(git clone git://github.com/syncfree/antidote_crdt .tmp_dir261497953176 -b 0.0.5 --single-branch)
failed with return code 128 and the following output:
Clonage dans '.tmp_dir261497953176'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connexion terminée par expiration du délai d'attente
github.com[1: 192.30.253.113]: errno=Connexion terminée par expiration du délai d'attente`

**Comment by ergl** [comment]
@adilbakkouri Does it work if you change `git://github...` for `https://github...`? I know I've had troubles in the past with those kind of dependencies while using some networks.

**Comment by adilbakkouri** [comment]
@ergl I used `git clone https://github.com/SyncFree/antidote.git` the first time and i had the same problem. it didnt work.

**Comment by peterzeller** [comment]
@adilbakkouri  Can you try to also change the URLs in `rebar.config` to use `https:` instead of `git:`? It could be that you are behind a proxy that does not allow ssh connections.

**Comment by adilbakkouri** [comment]
Finnaly , i resolve it just as @WoolridgeGrant did , i update all my packages : 
`aptitude update`
`aptitude full-upgrade`
 and it works directly when i retry,i still have no idea what was the problem!
Thank you for the suggestions.

**Comment by WoolridgeGrant** [comment]
@cmeiklejohn From the history command the only thing that could have solve the problem is to update the packages

@peterzeller I do believe that you have a solution to this problem, indeed I tried to execute the command that was blocking 'make rel' which is : 
> git clone git://github.com/syncfree/antidote_crdt
and that did not work, when putting https instead of git everything went well
