### ISSUE TITLE
problem building when fetching basho_stats

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#282]
Hi, I'm having a problem in the Physics-protocol-stable branch.
When trying to build, I get:

`===> Fetching rebar3_protobuffs_plugin ({git,
                                                "git://github.com/cmkarlsson/rebar3_protobuffs_plugin",
                                                {branch,"master"}})
===> Compiling rebar3_protobuffs_plugin
===> Fetching riak_pb_msgcodegen ({git,
                                          "git://github.com/tsloughter/riak_pb_msgcodegen",
                                          {branch,"master"}})
===> Compiling riak_pb_msgcodegen
===> Fetching basho_stats ({pkg,<<"basho_stats">>,<<"1.0.3">>,
                                      undefined})
**===> Failed to fetch and copy dep: {pkg,<<"basho_stats">>,<<"1.0.3">>,undefined}**
make: *** [rel] Error 1
`

has anyone seen that error? It happens even when making rebar.config files look like master, and removing rebar.lock

 thanks!

**Comment by bieniusa** [comment]
Using the master branch as dependency might be problematic - any changes there might break the build.

You might want to tag a version that used to work with your branch and then stick with that one.

**Comment by peterzeller** [comment]
I also had some problems with the hex-packages before. If I remember correctly, it worked after deleting the package cache (at `~/.cache/rebar3/`on my machine).

**Comment by aletomsic** [comment]
@bieniusa good point, thanks.

@peterzeller after removing that file, i get frozen like this: 

`mbp-alejandro:antidote alek$ rm -rf ~/.cache/rebar3/
mbp-alejandro:antidote alek$ make console
/Users/alek/antidote/rebar3 release
===> Package lager-3.2.1 not found. Fetching registry updates and trying again...
===> Updating package registry...`

**Comment by aletomsic** [comment]
@peterzeller that solver the issue. Thanks!
It seems that yesterday the rebar repos were down.
