### ISSUE TITLE
env attach not working in all Docker setups

### ISSUE THREAD

**Issue by mweberUKL** [SyncFree/antidote#301]
The script to attach to a running Antidote instance is not working in all Docker setups. It works when creating a dedicated network like so:

```
docker network create --driver bridge default_ntwk
docker run -i -t -d --name antidote --network default_ntwk -e SHORT_NAME=true -e NODE_NAME=antidote@antidote antidotedb/antidote
docker exec -it antidote /opt/antidote/bin/env attach
```

It also work when not given a node name:

```
docker run -i -t -d --name antidote antidotedb/antidote
docker exec -it antidote /opt/antidote/bin/env attach
```

What does not work, for example, is to give a different node name and use the default docker network:

```
docker run -i -t -d --name antidote -e SHORT_NAME=true -e NODE_NAME=antidote@antidote antidotedb/antidote
docker exec -it antidote /opt/antidote/bin/env attach
```

This give the following error:

```
$ docker exec -it antidote /opt/antidote/bin/env attach
IP address not set; defaulting to 127.0.0.1.
MESOS_TASK_ID:
PORT0:
PORT1:
PORT2:
PORT3:
PORT4:
NODE_NAME: antidote@antidote
COOKIE: antidote
IP: 127.0.0.1
HOSTNAME: c59160df7d69
Node is not running!
```

The `Node is not running!` comes from the check whether the node can be pinged.

## Setup

- macOS Sierra (10.12.4)
- Docker for Mac 17.06.0-rc1-ce-mac13 (Channel: edge)

**Comment by nherbaut** [comment]
@deepthidevaki any news on this issue ? maybe a workaround ?

**Comment by mweberUKL** [comment]
This is not a bug of Antidote but a feature of Docker. Docker does not offer any DNS service for the default network. This means that the name (in the failing example the hostname `antidote`) cannot be resolved.

If you run Antidote as a Docker container and need to attach to it, make sure that the provided hostname of the Antidote node can be resolved.
