### ISSUE TITLE
Type Check

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#84]
The way I see it, there are two possible directions to take from here.

The first one, which I think is the best in terms of performance and elegance, would be to perform the  type check as soon as a transaction starts. So, what this means is that the type check is the first task a tx coordinator should perform. So, the tx coord would call materialzer:type_check(Operations). The materialiser should check if for each op, the parameters sent are valid. The current implementation presents two problems for performing a complete check:
it does not embed the type in the key, so at this stage we can not check that the operations also respect that the type is the same as the one stored for that key (if it exists).
it does not include the type in update operations.

The second one (and easiest from the point the implementation is now) would be to perform the type check when generating the downstream operation. This presents the need of reading the key first in order to know its type and then see if the operation is supported and the parameters sent by the update are valid. Checking at this point would be expensive, as maybe many operations could have already generated its downstream. All the process of starting the coordinator, sending correct updates to partitions and then aborting the transaction will be done because of a wrong typed or bad parametrised operation.

I could start by doing the second approach (which could be pretty easy) and then discuss about implementing the first one. I await your comments.

**Comment by aletomsic** [comment]
Proposed solution for the new interface (see Deepthi’s thread “Andidote application/materialiser interface”):


If I understand correctly, the new interface will:

1) create buckets containing objects of the same type. How will this be implemented?
2) bind an object on its creation to a certain type. 
3) read and update operations will not take as a parameter the object type, as it will be embedded on the object's bucket.

Solution:
Whenever an object is handled inappropriately, a transaction will abort.
Inappropriate handling includes (please contribute to completing this list if I am missing anything):

* binding a key to a type that does not exist.
* using an undefined method for a given type, e.g. trying to increment a set.
* using a defined method's type with incorrect parameters.
* issuing an operation on a not bound key.

Remark: binding an already bound key simply generates a new key in a different bucket.


Implementation:


binding a key to a type that does not exist.

issue a type:new() operation at the coordinator. In case of success, continue; otherwise, abort the txn.

using an undefined method for a given type, e.g. trying to increment a set.
using a defined method's type with incorrect parameters.

for these cases, issue a type:operation(params) at the coordinator. Abort if fails.

issuing an operation on a not bound key.

this is the only tricky check, as it requires checking that the object exists, which means contacting the partition that stores the object. 
my suggestion is to perform this check optimistically, at downstream generation. It could be too late, but this way we would not incur in significant overhead.
for operations that do not require downstream generation, this check would need to perform a read to the object. 
if the case is that the object does not exist (has not been bound), the partition will send an abort message to the coordinator (this is done at the prepare face, when partitions vote on committing or aborting a txn), that will abort the transaction.

**Comment by aletomsic** [comment]
Annette, Marc,

The previous message explains how I am going to do it. 
Starting now.
Should not take much time.

**Comment by aletomsic** [comment]
pull request #142 

What I've done:

In the previous email I pointed out the problems that I am going to tackle:

1) binding a key to a type that does not exist.
2) using an undefined method for a given type, e.g. trying to increment a set.
3) using a defined method's type with incorrect parameters.
4) issuing an operation on a not bound key.

1 and 4) can not be solved right now as that functionality is not still included. Deepthi is working on the new interface, that does. Once the new interface is in place, that must be addressed.

2 and 3) addressed by this solution. I've created a function in the materialiser module which verifies for each operation being issued, if it's correctly typed, by performing that operation on an empty crdt. This function is now called in antidote.erl, before starting a coordinator fsm.

**Comment by cmeiklejohn** [comment]
Open question:

Why does this functionality exist in the materializer?  This means that the
operation can exist in the log, but not be applied.  Why are we not
preventing these operations from being inserted into the log?

**Comment by aletomsic** [comment]
El lunes, 14 de septiembre de 2015, Christopher S. Meiklejohn <
notifications@github.com> escribió:

> Open question:
>
> Why does this functionality exist in the materializer?


It exists in the materializer library, and not in the vnode.
It is done there because the type check performs a check which is dependent
on an object type and its operations with their parameters.


>  This means that the
> operation can exist in the log, but not be applied.


No, it can never reach the log, as the check is performed before sending an
operation to a transaction coordinator.


>  Why are we not
> preventing these operations from being inserted into the log?


>
>
> On Mon, Sep 14, 2015 at 4:05 AM, Alejandro Zlatko Tomsic <
> notifications@github.com

**Comment by cmeiklejohn** [comment]
Ah, alright.  Do we need to worry about concurrent transactions over the same key with different data types, given they won't merge correctly?

**Comment by aletomsic** [comment]
This case should be solves when we start embedding the type within an object’s key. 
Is that part of the interface change deepthi is working on?

**Comment by cmeiklejohn** [comment]
:+1: 

Embedding the type in the key is a great solution.
