### ISSUE TITLE
Optimization: group ops per partition in a static txn

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#95]
When a static_txn_coord is started with a list of operations, it issues it to the interactive_txn_coord, one by one. 
This optimization will group the operations at the static_txn_coord and send it to the interactive one in a grouped-per-partition fashion.
At the interactive coordinator, there will be a new function that will handle this new kind of request.

**Comment by aletomsic** [comment]
I am branching from the "evaluation" branch. If someone thinks I should branch from another one please let me know ASAP.

**Comment by aletomsic** [comment]
I should be able to finish this tomorrow at noon.

**Comment by aletomsic** [comment]
This is finished. It inclues the update optimizations made by Manuel, as I branched from the opt_buffer_writes

**Comment by angbrav** [comment]
I do not understand one thing. You group by partition, then send to the interactive coordinator. The interactive coordinator issues all read operations in parallel or sequentially per partition?

Manuel

**Comment by aletomsic** [comment]
The interactive coordinator works like in the prepare phase.
It sends all requests to all partitions (one by one), and then goes to a state where he collects the replies.
Is it clear?
