### ISSUE TITLE
Eventually-Consistent Antidote for benchmark

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#96]
Create an eventually-consistent version of antidote by removing causal consistency enforcement.

**Comment by aletomsic** [comment]
I'm taking this over now. The starting point will be the optimized branch: opt_buffer_read, that includes the latest modifications.

**Comment by marsleezm** [comment]
The throughput of EC branch is much higher than the throughput of evaluation branch (about 50%). Materializer may be the cause of the problem.

**Comment by bieniusa** [comment]
Li,

Chris started with some improvements in the evaluation branch yesterday, I will also work on the code and check the materializer this morning.
I will be on Mumble till lunch time.

Don’t forget to pull the changes!

Best regards,

Annette Bieniusa
TU Kaiserslautern
FB Informatik
PO Box 3049
67653 Kaiserslautern

bieniusa@cs.uni-kl.de <mailto:bieniusa@cs.uni-kl.de>

Office:Building 34, Room 416
Phone:+49 (0) 631 205 3958
Fax:+49 (0) 631 205 3420
